### ISSUE TITLE
Missing text for translation and one translation that isn't working

### ISSUE THREAD

**Issue by olivier-b-be** [csharpfritz/KlipTok.Translations#100]
While adding the Dutch translations for the newly added transcription texts I noticed one of the lines of text not being translated, `Results from clip title search for text` (visible in screenshot where I have the Dutch language active on the site). I also couldn't find it in the `en-US` json file.

Screenshot below with Dutch language active:
![translations-kliptok](https://user-images.githubusercontent.com/60689309/128767857-b44a559f-dbb2-46ca-8853-12e853e5ea5d.png)

Another thing you might notice on the screenshot above is the button isn't being translated. I tested both Dutch and German which both have `NextPage` translations available but neither of them have the translated version showing. The same goes for the `PreviousPage` button.

Screenshot below with German language active:
![translations-kliptok-de](https://user-images.githubusercontent.com/60689309/128768193-95fdb925-d61a-44f9-87c5-ae59a6365919.png)

**Comment by csharpfritz** [comment]
Added fix with commit 90fe87e89ac99f81d0f88b5f9ba89825dbf2de0a
