### ISSUE TITLE
RTL layout considerations

### ISSUE THREAD

**Issue by MrBen0x** [csharpfritz/KlipTok.Translations#113]
Hi Jeff,

RTL support has a lot of quirks that can make Kliptok uncomfortable to use for RTL users, here is some issues related to RTL layout I think you should consider. 

### Landing page
[![Landing page](https://i.ibb.co/BPZ9xgq/landing-page.jpg)](https://i.ibb.co/BPZ9xgq/landing-page.jpg)

 1. About link:
	Margin is set to margin-left: auto, 	must be changed to:
	```
	(in _speacing.scss:70)
	@media (min-width: 768px)
	.ml-md-auto, .mx-md-auto {
		margin-right: auto !important;
	}
	```
  2. Question mark is flipped:
	Arabic, Hebrew, and other languages that use right-to-left scripts commonly include numerals or include text written in the Latin or other scripts: both of these typically flow left-to-right within the overall right-to-left context.
	Question mark “?”, exclamation mark “!”, period “.”, etc. have the BiDi class O.N. ('Other Neutrals'), which means effectively that it adapts to the directionality of the surrounding text. To ensure those issues don't occur, you can use the `<bdi>` tag:
		```
   		<bdi>
			<div class="left">
	            <a class="twitchChannelName" href="/clip/AntediluvianCulturedSandwichKippa-0mcY7Mj3JpPMqMSB">yuno returns?</a>
	            <br>
	            <a class="twitchChannelName" href="fuslie" target="">fuslie</a> يلعب Just Chatting
	            <br>
	            تم التسجيل منذ 9 أيام
	              - سجل بواسطة wang633
		    </div>
	    </bdi>
	    ```

[click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi) for more details about `<bdi>` tag.

3. Font must be changed.
4. Ribbon should be rotated and aligned to the left:
	```
		(in _layout.scss:311)
		@media (min-width: 768px)
		.ribbon-container {
			width: 150px;
			height: 150px;
			overflow: hidden;
			position: absolute;
			top: 2rem;
			right: inherit;
			left: -3px;
			z-index: 2;
			margin-right: 11px;
		}
		
		@media (min-width: 768px)
		(in _layout.scss:323)
		.ribbon {
			font: 15px;
			color: #e6e6e6;
			text-align: center;
			text-shadow: rgb(0 0 0 / 80%)  0px 1px 0px;
			transform:  rotate(-45deg);
			position: relative;
			padding: 5px;
			left: 60px;
			top: 4.5rem;
			width: 300px;
			background-image: -webkit-gradient(linear,  left  top,  left  bottom,  from(#c83232),  to(#ff6464));
			box-shadow: 0px 0px 3px  rgb(0 0 0 / 30%);
		}
	```
#### Landing page after applying the above fixes
[![final landing page](https://i.ibb.co/LkcXfgB/landing-page-final.jpg)](https://i.ibb.co/LkcXfgB/landing-page-final.jpg)

### Clip page
[![Clip](https://i.ibb.co/rwVg48w/channel.jpg)](https://i.ibb.co/rwVg48w/channel.jpg)
1. Font must be changed and right aligned, also text box width should be 90%.
2. Title must be right aligned.
3. Font must be changed.
#### Clip page after applying the above fixes
[![final clip page](https://i.ibb.co/S3m5F0Y/clip-page-final.jpg)](https://i.ibb.co/S3m5F0Y/clip-page-final.jpg)
### About page
[![about page](https://i.ibb.co/Z653gPS/about-page.jpg)](https://i.ibb.co/Z653gPS/about-page.jpg)
Change .grid-container style to:
```
(in _layout.scss:251)
@media (min-width: 1200px)
.grid-container {
	height: 100%;
	display: flex;
	margin-top: 0;
	flex-direction: row;
	justify-content: flex-start;
}
```
#### About page after applying the fixes
[![final about page](https://i.ibb.co/dM3MGPs/about-page-final.jpg)](https://i.ibb.co/dM3MGPs/about-page-final.jpg)

### Status page
[![status page](https://i.ibb.co/TBkLnYr/status-page.jpg)](https://i.ibb.co/TBkLnYr/status-page.jpg)
Text must be right aligned.
#### Status page after applying the fixes
[![final status page](https://i.ibb.co/gS4GTFW/status-page-final.jpg)](https://i.ibb.co/gS4GTFW/status-page-final.jpg)

### Loading page
[![loading page](https://i.ibb.co/DCSk9Sm/loading.jpg)](https://i.ibb.co/DCSk9Sm/loading.jpg)
* Font must be changed.
* Text must be right aligned.

### Font recommendation
[Dubai Font](https://dubaifont.com) is a beautiful sans-serif typeface commissioned by the Government of Dubai in partnership with Microsoft and designed by a U.S.-based firm Monotype. It contains both Latin and Arabic script.

**Comment by csharpfritz** [comment]
The Dubai Font has restrictions on distribution and is not clear on its copyright.  I've sent a message to the maintainers to get more information, but for now I will try [Scheherazade font](https://fonts.google.com/specimen/Scheherazade#standard-styles) from Google fonts.

**Comment by csharpfritz** [comment]
I'm going to pass on updating the "Loading..." text as I want to replace that with a more streamlined experience

**Comment by csharpfritz** [comment]
This will be merged in my next deployment

**Comment by csharpfritz** [comment]
Thank you so much for your help with this!
