### ISSUE TITLE
missing datepicker strings

### ISSUE THREAD

**Issue by ptasznikarium** [csharpfritz/KlipTok.Translations#41]
Start and End date in date picker are missing from localization dictionary.

Those might be displayed as part of datepicker component.

![image](https://user-images.githubusercontent.com/49695985/111771951-329b8880-88a4-11eb-8924-b6dd7cb514c6.png)

**Comment by csharpfritz** [comment]
Ooh...  you're right.  I thought we might have been getting that translation as part of the Telerik component.

There's a little bit of code to write to integrate the Telerik localizer with our implementation.  I'm going to use the sample from @marin-bratanov on this page as inspiration for connecting our localizer to the component:
https://github.com/telerik/blazor-ui/blob/1ff5e737c53488e13ee1a26356127f2ee2f36a7a/common/localization/ClientLocalizationResx/Shared/Services/SampleResxLocalizer.cs#L6

**Comment by csharpfritz** [comment]
I'm going to publish what we have now... and add this integration in a patch later today or tomorrow

**Comment by marin-bratanov** [comment]
Indeed, these translations must come from the app. In the examples we have, there are .resx files with keys corresponding to the keys that the components will request from the Telerik components localization service. In this example, the framework is very kind to resolve that indexer for us, so you just have to tweak the resx files. The two keys for this are `DateRangePicker_Start` and `DateRangePicker_End`

The caveat is that the resx localizer from the framework compiles those files to a C# class that always goes in the codebase of the app, and if I remember right, we wanted the localizations to get downloaded on demand, only when needed. So, the actual service may have to do a bit more work here if we want it to fetch resources on demand (could probably be relatively easy by serializing the resx to a dictionary so you keep the easy indexer).

**Comment by csharpfritz** [comment]
> The caveat is that the resx localizer from the framework compiles those files to a C# class that always goes in the codebase of the app, and if I remember right, we wanted the localizations to get downloaded on demand, only when needed. So, the actual service may have to do a bit more work here if we want it to fetch resources on demand (could probably be relatively easy by serializing the resx to a dictionary so you keep the easy indexer).

Agreed -- it looks like a service can be written that bridges the `ITelerikStringLocalizer` and the [Toolbelt localizer](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText).  I'll tinker with this later today

**Comment by marin-bratanov** [comment]
I hope I don't miss this on the stream when it happens (but I don't have my hopes up :D) On the other hand, I'm joining Ed's stream tonight (12 ET for your side of the big lake) :D

**Comment by csharpfritz** [comment]
I don’t think I’ll stream this and just get the code working later today.  I’ll recap on Sunday so that it’s shared. 



Jeff

**Comment by csharpfritz** [comment]
Fixed with ef4e0ca
