### ISSUE TITLE
'Share channel' shuld have it's own description.

### ISSUE THREAD

**Issue by fstreicher** [csharpfritz/KlipTok.Translations#44]
### Expected behaviour:
The share button/icon on a streamers KlipTok page should read: `Share streamer` or `Share channel`

### Actual behaviour:
It share it's description with the `Share clip` button.
![image](https://user-images.githubusercontent.com/4518852/111871155-073e9980-8989-11eb-9fd6-f5859b3cab32.png)

**Comment by csharpfritz** [comment]
Good catch...  let's roll this in with the fix for the DateRangeChooser localization

**Comment by csharpfritz** [comment]
Got it!  Fixed with a994779
