### ISSUE TITLE
rtl language is changing json file formatting

### ISSUE THREAD

**Issue by MohammadAnsari98** [csharpfritz/KlipTok.Translations#79]
Hello, I'm trying to add a Persian language translation, but when I edit KlipTok.en.json and replace English words with Persian, the JSON file format changes, particularly "" location.

this is what happening
![Capture](https://user-images.githubusercontent.com/25693849/118355260-4a317d80-b584-11eb-85f1-9c7b7c896aab.PNG)

**Comment by csharpfritz** [comment]
This looks like its behaving properly with the code in the fa-IR file.  Please review that file and let's make sure it's presenting translations properly

**Comment by csharpfritz** [comment]
Tested and this is working properly with RTL languages in this format.  

No changes needed.

Thank you for raising awareness on this
